# Generated by Django 3.2.8 on 2021-12-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools_stats', '0014_auto_20211122_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedvalue',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='cachedvalue',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedvalue',
            name='dynamic_choices',
            field=models.JSONField(default=dict),
        ),
    ]
