# Generated by Django 4.0.8 on 2022-11-03 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tools_stats", "0017_alter_dashboardstats_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dashboardstats",
            options={"verbose_name": "dashboard stats", "verbose_name_plural": "dashboard stats"},
        ),
    ]
