# Generated by Django 4.0.8 on 2022-11-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tools_stats", "0018_alter_dashboardstats_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteriatostatsm2m",
            name="recalculate",
            field=models.BooleanField(
                default=False,
                verbose_name="Recalculate by management command (apply only for multiple series)",
            ),
        ),
    ]
