# Generated by Django 4.0.8 on 2022-12-01 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_tools_stats", "0019_criteriatostatsm2m_recalculate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboardstats",
            name="graph_key",
            field=models.CharField(
                help_text="it needs to be one word unique. ex. auth, mygraph",
                max_length=90,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9_]+$", "Only small alphanumeric characters and underscore allowed."
                    )
                ],
                verbose_name="graph identifier",
            ),
        ),
    ]
